### ISSUE TITLE
Approach: Build on top of gzdeflate()/gzinflate()

### ISSUE THREAD

**Issue by clue** [clue/php-zlib-react#2]
Refs #1.

**Comment by clue** [comment]
I've posted this ticket mostly for the reference only.

Both `gzdeflate()` and `gzinflate()` operate on a complete string buffer. This means you can not process individual _chunks_ of this buffer. As such, they're not an option for a streaming (de-)compressor.

For the reference: The overhead of processing individual chunks may be overkill if your maximum buffer size is limited. Some protocols actually emit (smaller) individual frames which use a DEFLATE compression. In this case, buffering the whole frame and then using the complete buffer is probably _okay_.

**Comment by staabm** [comment]
Php7 supports incremental gzip, see https://github.com/amphp/aerys/blob/master/lib/functions.php#L488

**Comment by clue** [comment]
Thanks @staabm! Are we talking about #4 here or do you have anything other in mind? :)

**Comment by staabm** [comment]
Exactly, https://github.com/amphp/aerys/blob/master/lib/functions.php#L538. Glad you already found it yourself :-)

**Comment by clue** [comment]
Thanks for sharing the link though! Having an example use case will certainly help implementing #4.
